linters:
  disable-all: true
  enable:
    - govet
    - gosimple
    - errcheck
    - staticcheck
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - misspell
    - maprangecheck

linters-settings:
  custom:
    maprangecheck:
      path: tools/maprangecheck/maprangecheck.so
      description: reports range statements over maps
      original-url: github.com/onflow/cadence/tools/maprangecheck


